kind: Deployment
apiVersion: apps/v1
metadata:
  name: portfolio
  namespace: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: minhdat97/portfolio
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always